// <auto-generated />
using System;
using LGRRS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LGRRS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LgrrsDbContext))]
    [Migration("20261001140055_SingleLgaDraw")]
    partial class SingleLgaDraw
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LGRRS.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("LGRRS.Domain.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActorRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("EventId");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("LGRRS.Domain.Entities.CatalogItem", b =>
                {
                    b.Property<Guid>("CatalogItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CatalogItemId");

                    b.HasIndex("MerchantId", "Name")
                        .IsUnique();

                    b.ToTable("CatalogItems");
                });

            modelBuilder.Entity("LGRRS.Domain.Entities.DrawPeriod", b =>
                {
                    b.Property<Guid>("DrawPeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CandidateSetCount")
                        .HasColumnType("int");

                    b.Property<string>("CandidateSetHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DrawDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LgaCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrizeBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("WinnerCount")
                        .HasColumnType("int");

                    b.HasKey("DrawPeriodId");

                    b.ToTable("DrawPeriods");
                });

            modelBuilder.Entity("LGRRS.Domain.Entities.DrawResult", b =>
                {
                    b.Property<Guid>("DrawResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DrawPeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DrawTimestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PrizeAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PrizeTier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DrawResultId");

                    b.HasIndex("DrawPeriodId");

                    b.HasIndex("EntryId")
                        .IsUnique();

                    b.ToTable("DrawResults");
                });

            modelBuilder.Entity("LGRRS.Domain.Entities.FraudFlag", b =>
                {
                    b.Property<Guid>("FlagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EntityType")
                        .HasColumnType("int");

                    b.Property<int>("RuleCode")
                        .HasColumnType("int");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("FlagId");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("FraudFlags");
                });

            modelBuilder.Entity("LGRRS.Domain.Entities.Merchant", b =>
                {
                    b.Property<Guid>("MerchantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusinessAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LagosTaxIdEncrypted")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LgaCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LgrrsSystemId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PasscodeFailedAttempts")
                        .HasColumnType("int");

                    b.Property<string>("PasscodeHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("PasscodeLockedUntil")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PhoneEncrypted")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset?>("PosApiKeyExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PosApiKeyHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PosApiKeyPrefix")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("PosIntegrationEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("ReviewReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("MerchantId");

                    b.HasIndex("LgrrsSystemId")
                        .IsUnique()
                        .HasFilter("[LgrrsSystemId] IS NOT NULL");

                    b.HasIndex("PhoneHash");

                    b.HasIndex("PosApiKeyHash")
                        .IsUnique()
                        .HasFilter("[PosApiKeyHash] IS NOT NULL");

                    b.ToTable("Merchants");
                });

            modelBuilder.Entity("LGRRS.Domain.Entities.OtpChallenge", b =>
                {
                    b.Property<Guid>("OtpChallengeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("int");

                    b.Property<Guid?>("MerchantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("OtpChallengeId");

                    b.HasIndex("MerchantId");

                    b.HasIndex("PhoneHash", "Purpose")
                        .IsUnique();

                    b.ToTable("OtpChallenges");
                });

            modelBuilder.Entity("LGRRS.Domain.Entities.PosSubmission", b =>
                {
                    b.Property<Guid>("PosSubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ExternalSaleId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PosSubmissionId");

                    b.HasIndex("MerchantId", "ExternalSaleId")
                        .IsUnique();

                    b.ToTable("PosSubmissions");
                });

            modelBuilder.Entity("LGRRS.Domain.Entities.PrizeClaim", b =>
                {
                    b.Property<Guid>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountNumberEncrypted")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankNameEncrypted")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimRef")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DrawResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NameEncrypted")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ClaimId");

                    b.HasIndex("ClaimRef")
                        .IsUnique();

                    b.HasIndex("DrawResultId")
                        .IsUnique();

                    b.ToTable("PrizeClaims");
                });

            modelBuilder.Entity("LGRRS.Domain.Entities.Receipt", b =>
                {
                    b.Property<Guid>("ReceiptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhoneEncrypted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhoneHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CustomerPhoneMasked")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DrawPeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ItemService")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("PaperClaimExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PaperClaimHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset?>("PaperClaimedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TransactionDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ReceiptId");

                    b.HasIndex("CustomerPhoneHash");

                    b.HasIndex("DrawPeriodId");

                    b.HasIndex("MerchantId");

                    b.HasIndex("PaperClaimHash")
                        .IsUnique()
                        .HasFilter("[PaperClaimHash] IS NOT NULL");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("LGRRS.Domain.Entities.ReceiptDelivery", b =>
                {
                    b.Property<Guid>("DeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Channel")
                        .HasColumnType("int");

                    b.Property<string>("DestinationMasked")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProviderRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("DeliveryId");

                    b.HasIndex("ReceiptId");

                    b.ToTable("ReceiptDeliveries");
                });

            modelBuilder.Entity("LGRRS.Domain.Entities.RewardEntry", b =>
                {
                    b.Property<Guid>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DrawPeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EligibilityStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RiskStatus")
                        .HasColumnType("int");

                    b.HasKey("EntryId");

                    b.HasIndex("DrawPeriodId");

                    b.HasIndex("ReceiptId")
                        .IsUnique();

                    b.HasIndex("ReceiptId", "DrawPeriodId")
                        .IsUnique();

                    b.ToTable("RewardEntries");
                });

            modelBuilder.Entity("LGRRS.Domain.Entities.SaleReport", b =>
                {
                    b.Property<Guid>("SaleReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BusinessLocation")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Issue")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LgaCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("PurchaseDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ReporterPhoneHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ReviewNote")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("SaleReportId");

                    b.HasIndex("Fingerprint")
                        .IsUnique();

                    b.HasIndex("ReporterPhoneHash", "CreatedAt");

                    b.ToTable("SaleReports");
                });

            modelBuilder.Entity("LGRRS.Domain.Entities.CatalogItem", b =>
                {
                    b.HasOne("LGRRS.Domain.Entities.Merchant", "Merchant")
                        .WithMany()
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("LGRRS.Domain.Entities.DrawResult", b =>
                {
                    b.HasOne("LGRRS.Domain.Entities.DrawPeriod", "DrawPeriod")
                        .WithMany("DrawResults")
                        .HasForeignKey("DrawPeriodId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LGRRS.Domain.Entities.RewardEntry", "Entry")
                        .WithOne("DrawResult")
                        .HasForeignKey("LGRRS.Domain.Entities.DrawResult", "EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DrawPeriod");

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("LGRRS.Domain.Entities.OtpChallenge", b =>
                {
                    b.HasOne("LGRRS.Domain.Entities.Merchant", "Merchant")
                        .WithMany()
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("LGRRS.Domain.Entities.PosSubmission", b =>
                {
                    b.HasOne("LGRRS.Domain.Entities.Merchant", "Merchant")
                        .WithMany()
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("LGRRS.Domain.Entities.PrizeClaim", b =>
                {
                    b.HasOne("LGRRS.Domain.Entities.DrawResult", "DrawResult")
                        .WithOne("PrizeClaim")
                        .HasForeignKey("LGRRS.Domain.Entities.PrizeClaim", "DrawResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DrawResult");
                });

            modelBuilder.Entity("LGRRS.Domain.Entities.Receipt", b =>
                {
                    b.HasOne("LGRRS.Domain.Entities.DrawPeriod", "DrawPeriod")
                        .WithMany()
                        .HasForeignKey("DrawPeriodId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LGRRS.Domain.Entities.Merchant", "Merchant")
                        .WithMany("Receipts")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DrawPeriod");

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("LGRRS.Domain.Entities.ReceiptDelivery", b =>
                {
                    b.HasOne("LGRRS.Domain.Entities.Receipt", "Receipt")
                        .WithMany("Deliveries")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("LGRRS.Domain.Entities.RewardEntry", b =>
                {
                    b.HasOne("LGRRS.Domain.Entities.DrawPeriod", "DrawPeriod")
                        .WithMany("RewardEntries")
                        .HasForeignKey("DrawPeriodId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LGRRS.Domain.Entities.Receipt", "Receipt")
                        .WithOne("RewardEntry")
                        .HasForeignKey("LGRRS.Domain.Entities.RewardEntry", "ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DrawPeriod");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("LGRRS.Domain.Entities.DrawPeriod", b =>
                {
                    b.Navigation("DrawResults");

                    b.Navigation("RewardEntries");
                });

            modelBuilder.Entity("LGRRS.Domain.Entities.DrawResult", b =>
                {
                    b.Navigation("PrizeClaim");
                });

            modelBuilder.Entity("LGRRS.Domain.Entities.Merchant", b =>
                {
                    b.Navigation("Receipts");
                });

            modelBuilder.Entity("LGRRS.Domain.Entities.Receipt", b =>
                {
                    b.Navigation("Deliveries");

                    b.Navigation("RewardEntry");
                });

            modelBuilder.Entity("LGRRS.Domain.Entities.RewardEntry", b =>
                {
                    b.Navigation("DrawResult");
                });
#pragma warning restore 612, 618
        }
    }
}
